language: python
python:
  - 2.6
  - 2.7
before_install:
  - pip install numpy > /dev/null
  - pip install nose > /dev/null
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install numexpr
  - pip install cython
  - pip install tables
install:
  - python setup.py install
script:
  - nosetests