language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true
  - export CC=gcc
  - export CXX=g++

script:
  - source deactivate
  - conda config --add channels https://conda.binstar.org/omnia
  - conda install --yes conda-build
  - conda build devtools/conda-recipe
  - source activate $python
  - conda install --yes $HOME/miniconda/conda-bld/linux-64/mdtraj-dev-*
  - conda list -e
  - pydir=$(which python); $precmd $(dirname $pydir)/nosetests --exclude-dir=MDTraj/html --with-coverage --cover-erase -vv
  - #cd devtools/c-tests/; make valgrind; cd -

env:
  matrix:
    - python=2.6  CONDA_PY=26  CONDA_NPY=16
    - python=2.7  CONDA_PY=27  CONDA_NPY=16
    - python=3.3  CONDA_PY=33  CONDA_NPY=17
    - python=3.4  CONDA_PY=34  CONDA_NPY=18

  global:
    # encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to push documentation to S3
    - secure: "qrbibHwlbXBTq+8h1DC1plyUcl67qwn5yr4UYILdk9WsBhPdNT0ObpRUOcFDW/YM9RDfcOvx7Ruq/OPhvlVCg1C+Lj01kSx3vHxYCxFJVyN7iiD9oI/xzFUc6guvYF9O8um2+QE1ZI70yffGJGT7MZUQNUBnKchqvV3uIeSOqw4="
    - secure: "Y4deQNbKXm0dTth0VoR59wEPYr0dNmp4Np+GDnJofwL+HKQ/w3dTrM3PQOV3bZ2w7WV2gAdtOv8MMUjdFYyyB+GS1wIZa4XbXchGNJr/lljvT3OP579ZwSLAowjEFFR6hidFDfMcR4D7KzTnoCIe9odXrZplI6l0M4OL1agki84="
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "YdOr8FF3Vw8FzMUYDOB6NSuet3Vh2YxHw9Q1pRu5SsSv3hgLeWIf1wlWOwEHmxU03oLD6DVrqvhStmYWZHunsQqziwGIUuqLxGXC0/dM//ayzfNObU266Pyy50Xn7+/J6YpRSrmMF/GaQeJbq0c357cIMSYRHg8izSaFYPOXKjs="

after_success:
  - echo "after_success"
  - source devtools/ci/after_sucess.sh
