# We pretend to be C because we can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them

# whitelist
branches:
  only:
    - master

language: c
before_install:
  - sudo add-apt-repository -y  ppa:fkrull/deadsnakes
  - sudo apt-get update
  # --------------------------------------------------------
  # Python2.7 stuff. Install as much as possible through apt
  # ---------------------------------------------------------
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq libhdf5-serial-dev
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-dev
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-numpy
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-scipy
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-nose
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-setuptools
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq cython
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-numexpr
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-tables
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq netcdf-bin libnetcdf-dev
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-setuptools
  - [[ $PYTHON == "python" ]] && sudo apt-get install -qq python-pandas
  - [[ $PYTHON == "python" ]] && sudo easy_install pip

  # Currently (august 11, 2013), the latest version of netcdf4-python
  # requires at least libnetcdf4-4.1.2, whereas apt-get libnetcdf-dev
  # is installing libnetcdf4-4.1.1. We're avoiding this issue by requiring
  # the previous release of netcdf4-python. Hopefully in the future this
  # can be resolved.
  # See https://code.google.com/p/netcdf4-python/issues/detail?id=194&start=100
  # https://github.com/rmcgibbo/mdtraj/pull/151
  # https://github.com/rmcgibbo/mdtraj/issues/150
  - [[ $PYTHON == "python" ]] && sudo pip install --use-mirrors netCDF4==1.0.4
  - [[ $PYTHON == "python" ]] && sudo pip install --use-mirrors flake8
  - [[ $PYTHON == "python" ]] && sudo pip install --use-mirrors scripttest
  - [[ $PYTHON == "python" ]] && sudo pip install --use-mirrors cffi
  - [[ $PYTHON == "python" ]] && sudo pip install git+git://github.com/rmcgibbo/simtk.unit

  # --------------------------------------------------------
  # Python3.2 stuff. Install as much as possible through apt
  # ---------------------------------------------------------
  - [[ $PYTHON == "python3" ]] && sudo apt-get install -qq python3-dev
  - [[ $PYTHON == "python3" ]] && sudo apt-get install -qq python3-setuptools
  - [[ $PYTHON == "python3" ]] && sudo apt-get install -qq python3-numpy
  - [[ $PYTHON == "python3" ]] && sudo apt-get install -qq python3-scipy
  - [[ $PYTHON == "python3" ]] && sudo easy_install3 pip
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install --use-mirrors numexpr
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install --use-mirrors cython
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install --use-mirrors tables
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install --use-mirrors cffi
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install --use-mirrors netCDF4==1.0.4
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install --use-mirrors scripttest
  - [[ $PYTHON == "python3" ]] && sudo pip-3.2 install git+git://github.com/rmcgibbo/simtk.unit


script:
  - sudo $PYTHON setup.py -q install
  - $PYTHON -c "import netCDF4; print(netCDF4.__version__)"
  - nosetests

env:
  matrix:
    - PYTHON=python
    - PYTHON=python3
  global:
    # encrypted AWS_SECRET_ACCESS_KEY to push documentation to S3
    - secure: "d3xpZOaixS6TyYTjOSPvIdwUYrTfuEM9sN8AxZKp/92sfcHj3EP7qyCMj/cuf1Gl7mT2nZJj4daOgMam4/sZD6MUnXokDwEgIMes2rrVjQX0i0MvXFU1LN8KbUcK+6QQyXc8AwxJJ603L9YxLnBdPfYTQNrd3zP7BzWYP00Nch4="

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then echo "This is a pull request. No deployment will be done."; exit 0; fi
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "No deployment on BRANCH='$TRAVIS_BRANCH'"; exit 0; fi
  - sudo apt-get install -qq python-sphinx       # for building documentation
  - sudo apt-get install -qq python-boto         # for interacting with S3
  - sudo apt-get install -qq python-sklearn      # for running example_pca.py
  - sudo apt-get install -qq python-matplotlib   # for custom sphinx extensions
  - sudo pip install ipython
  - cd docs && make html && cd -
  - python tools/travis-artifacts.py

