package:
  name: mdtraj
  version: !!str dev

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - pytables
    - pandas
    - scipy

test:
  # Python imports
  imports:
    - mdtraj

about:
  home: http://mdtraj.org
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
